# Generated by Django 5.2.7 on 2025-10-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('languages', models.TextField(help_text='Comma-separated languages')),
                ('education1', models.TextField()),
                ('education2', models.TextField(blank=True, null=True)),
                ('education3', models.TextField(blank=True, null=True)),
                ('project1', models.TextField()),
                ('project2', models.TextField(blank=True, null=True)),
                ('experience1', models.TextField()),
                ('experience2', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(help_text='Comma-separated achievements')),
            ],
        ),
    ]
