# Generated by Django 5.2.9 on 2026-06-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_resume_achievements_remove_resume_education1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='section_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
