# Generated by Django 5.2.9 on 2026-07-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_resume_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Application deadline', null=True),
        ),
    ]
