# Generated by Django 5.2.9 on 2026-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_jobapplication_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, help_text="Optional CV title (e.g., 'Data Analyst CV')", max_length=200, null=True),
        ),
    ]
