# Generated by Django 5.2.9 on 2026-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_education_is_current_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
