# Generated by Django 5.2.9 on 2026-07-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_education_is_current_experience_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('follow_up', 'Follow-up'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='saved', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='applications', to='cv.tag'),
        ),
    ]
