# Generated by Django 5.2.9 on 2026-07-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_tag_jobapplication_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='highest_stage_reached',
            field=models.IntegerField(choices=[(0, 'Saved'), (1, 'Applied'), (2, 'Follow-up'), (3, 'Interviewing'), (4, 'Offered')], default=0, help_text='Highest stage ever reached'),
        ),
    ]
