version: '3.8'

services:
  ddeep:
    build:
      context: .
      dockerfile: apps/ddeep/Dockerfile
    container_name: ddeep-app
    restart: unless-stopped
    networks:
      - proxy_network

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: admin-app
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
