import os

ENABLE_PROXY_FIX = True
FEATURE_FLAGS = {"EMBEDDED_SUPERSET": True}

SECRET_KEY = os.environ.get("SUPERSET_SECRET_KEY")
SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL")

REDIS_HOST = "superset-redis"
REDIS_PORT = "6379"

CACHE_CONFIG = {
    'CACHE_TYPE': 'RedisCache',
    'CACHE_DEFAULT_TIMEOUT': 300,
    'CACHE_KEY_PREFIX': 'superset_',
    'CACHE_REDIS_HOST': REDIS_HOST,
    'CACHE_REDIS_PORT': REDIS_PORT,
    'CACHE_REDIS_DB': 1,
}
DATA_CACHE_CONFIG = CACHE_CONFIG
