version: '3.9'

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami-app
    environment:
      DATABASE_URL: postgresql://umami:Str0ngDbP@ssw0rd!@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: DDeep_Super_Secret_Key_2026! # You can change this to any random string
    depends_on:
      - umami-db
    networks:
      - proxy_network
      - umami_internal
    restart: unless-stopped

  umami-db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: Str0ngDbP@ssw0rd!
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - umami_internal
    restart: unless-stopped

networks:
  proxy_network:
    external: true
  umami_internal:

volumes:
  umami-db-data:
