# Generated by Django 5.2.9 on 2026-07-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emaillogincode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pdfexport',
            name='user',
        ),
        migrations.AddField(
            model_name='emaillogincode',
            name='pdf_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to='pdf_converter.pdfuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfexport',
            name='pdf_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_converter.pdfuser'),
        ),
        migrations.AlterField(
            model_name='pdftemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_converter.pdfuser'),
        ),
    ]
