# Generated by Django 5.2.9 on 2026-07-16 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_converter', '0002_pdfuser_remove_emaillogincode_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfexport',
            name='conversion_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pdfexport',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfexport',
            name='source_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pdfuser',
            name='api_key_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfuser',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdfuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pdfuser',
            name='total_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfuser',
            name='total_uploads',
            field=models.IntegerField(default=0),
        ),
    ]
