name: Deploy Frontend Architecture

# Only trigger this pipeline when code is pushed to the main branch...
on:
  push:
    branches:
      - main
    # ...AND only if the files changed were inside the frontend folders!
    paths:
      - 'apps/forms/frontend/**'
      - 'apps/ddeep/**'
      - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Trigger VPS Frontend Deployment Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # This tells GitHub to run your exact bash script on the server
          script: |
            cd /opt
            chmod +x deploy_mr.sh
            /opt/deploy-wrapper.sh 6ef34dab-51a1-4ff7-8e36-6cdd92f034c6 forms /opt/deploy_mr.sh
